version: "3.8"

volumes:
  postgres_data:

networks:
  mainnet:

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    command: npm run start
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    restart: "on-failure"
    networks:
      - mainnet
    depends_on:
      - postgres

  postgres:
    image: "postgres:14-alpine"
    env_file:
      - .env.production
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - mainnet
